name: .NET Core

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore MincePieRateV2
    - name: Build
      run: dotnet build MincePieRateV2 --configuration Release --no-restore
    - name: Test
      run: dotnet test MincePieRateV2 --no-restore --verbosity normal
